name: linux

on: 
  push:
    path:
      - 'linux'

jobs:
  build: 
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout major release
      uses: actions/checkout@v2           
    - name: Install Dependencies
      run: ./install-deps.sh
    - name: Check Clean Build of Downstream Linux Tree
      run: |
          linuxCommitHash=$(git rev-parse HEAD:linux) 
          wget https://github.com/dejiezhen/linux/archive/${linuxCommitHash).zip
          echo 'Passed step 1'
          unzip linux-$(linuxCommitHash).zip
          echo 'Passed step 2'
          ./build-linux.sh linux-$(linuxCommitHash) tinyconfig


