name: linux

on: 
    push:

jobs:
    build: 
        runs-on: ubuntu-20.04
        
        steps:
        -name: Checkout major version of release
        uses: actions/checkout@v2
           
        -name: Install Dependencies
        run: ./install-deps.sh

