name: linux

on: 
  push:
    path: 
      - 'linux'

jobs:
  build: 
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout major release
      uses: actions/checkout@v2           
    - name: Install Dependencies
      run: ./install-deps.sh

