name: linux

on: 
  push:
    paths:
      - 'linux'

jobs:
  build: 
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout major release
      uses: actions/checkout@v2          
    - name: Install Dependencies
      run: ./install-deps.sh
    - name: Download Linux and unzip folder
      run: |
        linuxHash=$(git rev-parse HEAD:linux)
        wget -q https://github.com/dejiezhen/linux/archive/${linuxHash}.zip
        unzip -q ${linuxHash}.zip
    - name: Build Linux with tinyconfig
      run: |
        linuxHash=$(git rev-parse HEAD:linux)
        ./build-linux.sh linux-${linuxHash} tinyconfig
         
