name: linux

on: 
  push:
    paths:
      - 'linux/**'

jobs:
  build: 
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout major release
      uses: actions/checkout@v2 
      with: 
        submodules: true          
    - name: Install Dependencies
      run: ./install-deps.sh
    - name: Download linux and unzip folder
      run: |
        linuxHash=$(git rev-parse HEAD:linux)
        wget https://github.com/dejiezhen/linux/archive/${linuxHash}.zip
        ls -all
        unzip ${linuxHash}.zip
        ./build-linux.sh linux-${linuxHash} tinyconfig
         
