name: test

on: 
  push:
    paths:
     - 'test/**'

jobs:
  build: 
    runs-on: ubuntu-20.04

    steps: 
      - name: Check out major release
        uses: actions/checkout@v2
      - name: make test 
        run: make -C test 
